### PR TITLE
Fix for selinux policy constantly being processed

### LINKED ISSUE #1842: SelinuxProfile never finishes reconcilation and causes semodule to use 100% cpu
#### What happened:
When applying an SelinuxProfile to a K8s cluster running the security-profiles-operator, the semodule process on the node uses 100% cpu. This appears to be caused by the operator constantly detecting a drift between the applied policy on the node and what is stored in the CRD. For each detection of a drift, the operator attempts to install the policy again. However, since the operator does not currently care about order in the Selinux policy it changes each time which triggers another drift. Since the policy is constantly changing, semodule runs constantly and attempts to install the selinux policy.

#### What you expected to happen:
The operator to only install / change the policy if the upstream CRD has changed and therefore semodule only runs for actual changed policy.

#### How to reproduce it (as minimally and precisely as possible):
Apply an SelinuxProfile CRD with selinux in enforcement mode.

#### Anything else we need to know?:
no

#### Environment:
RHEL8

### PR DESCRIPTION
**Pull request by novaesis**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Sorts the allow rules in the selinux policy when doing the write to the node and doing the comparison between CRD and node policy which allows for consistent comparisons.

#### Which issue(s) this PR fixes:
Fixes #1842 

#### Does this PR have test?
N/A

#### Does this PR introduce a user-facing change?
```release-note
Fixed selinux policy constantly being processed.
```

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm
really nice work, thank you. Let's see if the tests pass!

File: internal/pkg/util/maps.go [hunk 1]
```diff
@@ -0,0 +1,12 @@
+package util
```
Comment (saschagrunert) [inline internal/pkg/util/maps.go:1]: CI complains about:

```
1 files have incorrect boilerplate headers:
internal/pkg/util/maps.go
```

**Comment by novaesis** [comment]
@saschagrunert fixed the issue the CI was complaint about. The other two build issues appear not related to this PR.

**Review by saschagrunert — APPROVED** [review]
Thank you!
