### PR TITLE
fix - builds for darwin

### LINKED ISSUE #182: make all fails
#### What happened:
I have forked the repo and try to run make and it failed.

#### What you expected to happen:
make to succeed 

#### How to reproduce it (as minimally and precisely as possible):
```
make all
mkdir -p build
go build -ldflags '-s -w -linkmode external -extldflags "-static" -X sigs.k8s.io/security-profiles-operator/internal/pkg/version.buildDate='2021-01-12T16:15:06Z' -X sigs.k8s.io/security-profiles-operator/internal/pkg/version.gitCommit=c7f337312e70b657af8e8c51b9310c47ea74f2a7 -X sigs.k8s.io/security-profiles-operator/internal/pkg/version.gitTreeState=clean -X sigs.k8s.io/security-profiles-operator/internal/pkg/version.version=0.3.0-dev' -tags 'netgo osusergo' -o build/security-profiles-operator ./cmd/security-profiles-operator
# github.com/containers/common/pkg/seccomp
../../../../pkg/mod/github.com/containers/common@v0.29.0/pkg/seccomp/supported.go:38:12: undefined: unix.Prctl
../../../../pkg/mod/github.com/containers/common@v0.29.0/pkg/seccomp/supported.go:38:23: undefined: unix.PR_GET_SECCOMP
../../../../pkg/mod/github.com/containers/common@v0.29.0/pkg/seccomp/supported.go:40:13: undefined: unix.Prctl
../../../../pkg/mod/github.com/containers/common@v0.29.0/pkg/seccomp/supported.go:40:24: undefined: unix.PR_SET_SECCOMP
../../../../pkg/mod/github.com/containers/common@v0.29.0/pkg/seccomp/supported.go:40:45: undefined: unix.SECCOMP_MODE_FILTER
make: *** [build/security-profiles-operator] Error 2
```

#### Anything else we need to know?:
A better contributing guide would be helpful. I will do a PR to bootstrap when I can get past this.

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): osx
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by naveensrinivasan**
#### What type of PR is this?
The darwin builds are fixed.
/kind bug

#### What this PR does / why we need it:
The osx builds were broken and this fixes it.

#### Which issue(s) this PR fixes:
Fixes #182 

#### Special notes for your reviewer:
The `containers/common` v0.32.0 specifically addressed osx build failures.

#### Does this PR introduce a user-facing change?
NONE

```release-note
NONE
```

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@saschagrunert  I was able to move forward. But still, some tests are failing.
```
make test-unit
go test -ldflags '-X sigs.k8s.io/security-profiles-operator/internal/pkg/version.buildDate='2021-01-14T01:08:39Z' -X sigs.k8s.io/security-profiles-operator/internal/pkg/version.gitCommit=272d5e37d8def4c16a53fe228f986291f2bc2e3b -X sigs.k8s.io/security-profiles-operator/internal/pkg/version.gitTreeState=clean -X sigs.k8s.io/security-profiles-operator/internal/pkg/version.version=0.3.0-dev' -v -test.coverprofile=build/coverage.out ./internal/...
?   	sigs.k8s.io/security-profiles-operator/internal/pkg/config	[no test files]
=== RUN   TestReconcile
=== RUN   TestReconcile/ProfileNotFound
--- FAIL: TestReconcile (0.00s)
    --- FAIL: TestReconcile/ProfileNotFound (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1e396d5]

goroutine 25 [running]:
testing.tRunner.func1.1(0x1f28740, 0x2a4fb30)
	/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc0003a2300)
	/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1075 +0x41a
panic(0x1f28740, 0x2a4fb30)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:969 +0x1b9
sigs.k8s.io/security-profiles-operator/internal/pkg/controllers/profile.(*Reconciler).Reconcile(0xc00015a8c0, 0x208f8f8, 0xe, 0x208dbc8, 0xc, 0x5a7c63f0fa00, 0x0, 0x0, 0x0)
	/Users/naveen/go/src/github.com/naveensrinivasan/security-profiles-operator/internal/pkg/controllers/profile/profile.go:166 +0x435
sigs.k8s.io/security-profiles-operator/internal/pkg/controllers/profile.TestReconcile.func2(0xc0003a2300)
	/Users/naveen/go/src/github.com/naveensrinivasan/security-profiles-operator/internal/pkg/controllers/profile/profile_test.go:96 +0x6b
testing.tRunner(0xc0003a2300, 0xc0003da9e0)
	/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1168 +0x2b3
FAIL	sigs.k8s.io/security-profiles-operator/internal/pkg/controllers/profile	0.600s
?   	sigs.k8s.io/security-profiles-operator/internal/pkg/controllers/selinuxpolicy	[no test files]
=== RUN   Test_getEffectiveSPOd
=== RUN   Test_getEffectiveSPOd/Should_correctly_set_the_image
=== RUN   Test_getEffectiveSPOd/Should_correctly_set_the_namespace
--- PASS: Test_getEffectiveSPOd (0.01s)
    --- PASS: Test_getEffectiveSPOd/Should_correctly_set_the_image (0.01s)
    --- PASS: Test_getEffectiveSPOd/Should_correctly_set_the_namespace (0.00s)
PASS
coverage: 16.7% of statements
ok  	sigs.k8s.io/security-profiles-operator/internal/pkg/controllers/spod	0.323s	coverage: 16.7% of statements
?   	sigs.k8s.io/security-profiles-operator/internal/pkg/controllers/spod/bindata	[no test files]
=== RUN   TestVersionText
--- PASS: TestVersionText (0.00s)
=== RUN   TestVersionJSON
--- PASS: TestVersionJSON (0.00s)
PASS
coverage: 93.8% of statements
ok  	sigs.k8s.io/security-profiles-operator/internal/pkg/version	0.150s	coverage: 93.8% of statements
FAIL
make: *** [test-unit] Error 1
```

**Comment by saschagrunert** [comment]
/ok-to-test

@naveensrinivasan usually there should no segmentation fault, but I also do not expect that the operator works on macOS at all. macOS has no support for seccomp, right?

**Comment by naveensrinivasan** [comment]
> /ok-to-test
> 
> @naveensrinivasan usually there should no segmentation fault, but I also do not expect that the operator works on macOS at all. macOS has no support for seccomp, right?

@saschagrunert  Yes, I don't expect it to work on macos. If I am not wrong some of the tests shouldn't fail even on macos.

**Comment by pjbgf** [comment]
@naveensrinivasan the issue here is that `seccomp.IsSupported` is always returning `false`. I made a few changes on a separate PR that should change that. 

Now to get this to work in Darwin you might need to:
- skip `TestReconcile` if `!seccomp.IsSupported`
- remove `seccomp` tag when in Darwin

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan the issue here is that `seccomp.IsSupported` is always returning `false`. I made a few changes on a separate PR that should change that.
> 
> Now to get this to work in Darwin you might need to:
> 
> * skip `TestReconcile` if `!seccomp.IsSupported`
> * remove `seccomp` tag when in Darwin

@pjbgf I fixed the test and now it is working.

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan the issue here is that `seccomp.IsSupported` is always returning `false`. I made a few changes on a separate PR that should change that.
> 
> Now to get this to work in Darwin you might need to:
> 
> * skip `TestReconcile` if `!seccomp.IsSupported`
> * remove `seccomp` tag when in Darwin

@pjbgf Thanks, I was able to fix the issues and also included a GitHub pipeline to run checks against macOS. I tried enabling `e2e` tests on GitHub Pipeline but it failed because `macOS` does not have `docker` installed in it.

Let me know if there is anything else.

**Comment by JAORMX** [comment]
@naveensrinivasan Maybe I'm missing something, but if Seccomp is not supported at all in MacOS... why are you trying to build for that? They also don't support SELinux. It seems to me like this operator will be unusable in that architecture.

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan Maybe I'm missing something, but if Seccomp is not supported at all in MacOS... why are you trying to build for that? They also don't support SELinux. It seems to me like this operator will be unusable in that architecture.

@JAORMX I agree that Seccomp and SELinux are not supported on OSX. The reason I am trying to build on OSX is to make contributions to this repository from non-Linux OS. 

Lots of engineers including me use OSX as the main dev box and it makes it harder to switch over to Linux to contribute to this repository. For example, none of the `k8s` operators can directly run on `osx` but the contributors are not contrived to a single OS.

The goal is to encourage devs to contribute to this repository also provide a comprehensive contributing guide similar to this https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#what-to-do-before-submitting-a-pull-request , so it clearly communicates what can run locally and how can it be tested (unit and e2e).

Hope this answers your questions, would be more than happy to discuss if you have other thoughts 😄

**Comment by JAORMX** [comment]
> > @naveensrinivasan Maybe I'm missing something, but if Seccomp is not supported at all in MacOS... why are you trying to build for that? They also don't support SELinux. It seems to me like this operator will be unusable in that architecture.
> 
> @JAORMX I agree that Seccomp and SELinux are not supported on OSX. The reason I am trying to build on OSX is to make contributions to this repository from non-Linux OS.
> 
> Lots of engineers including me use OSX as the main dev box and it makes it harder to switch over to Linux to contribute to this repository. For example, none of the `k8s` operators can directly run on `osx` but the contributors are not contrived to a single OS.
> 
> The goal is to encourage devs to contribute to this repository also provide a comprehensive contributing guide similar to this https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#what-to-do-before-submitting-a-pull-request , so it clearly communicates what can run locally and how can it be tested (unit and e2e).
> 
> Hope this answers your questions, would be more than happy to discuss if you have other thoughts smile

oh! I understand now, the intent is not to have the operator run on OSX, but to just be able to build it. Got it! Thanks for the explanation.

LGTM

**Review by JAORMX — APPROVED** [review]

File: Makefile [hunk 1]
```diff
@@ -88,7 +89,11 @@ $(BUILD_DIR):
 	mkdir -p $(BUILD_DIR)
 
 $(BUILD_DIR)/$(PROJECT): $(BUILD_DIR) $(BUILD_FILES)
+ifneq ($(shell uname -s), Darwin)
 	$(GO) build -ldflags '$(LDFLAGS)' -tags '$(BUILDTAGS)' -o $@ ./cmd/security-profiles-operator
+else
+	$(GO) build -ldflags '$(LDFLAGS)' -tags '$(BUILDTAGSOSX)' -o $@ ./cmd/security-profiles-operator
+endif
```
Comment (saschagrunert) [inline Makefile:96]: I'd prefer that we just set the `BUILDTAGS` differently when running on macOS. This way we can avoid code duplication.

File: test/suite_test.go [hunk 2]
```diff
@@ -105,11 +107,21 @@ func (e *kinde2e) SetupSuite() {
 	e.Nil(os.MkdirAll(buildDir, 0o755))
 
 	e.kindPath = filepath.Join(buildDir, "kind")
-	e.downloadAndVerify(
-		"https://github.com/kubernetes-sigs/kind/releases/download/"+
-			kindVersion+"/kind-linux-amd64",
-		e.kindPath, kindSHA512,
-	)
+	operatingSystem := runtime.GOOS
+	switch operatingSystem {
```
Comment (saschagrunert) [inline test/suite_test.go:111]: No need to bind a variable here 
```suggestion
	switch runtime.GOOS {
```

File: test/suite_test.go [hunk 3]
```diff
@@ -105,11 +107,21 @@ func (e *kinde2e) SetupSuite() {
...
+	case "darwin":
+		e.downloadAndVerify(
+			"https://github.com/kubernetes-sigs/kind/releases/download/"+
+				kindVersion+"/kind-darwin-amd64",
+			e.kindPath, kindOSXSHA512,
+		)
```
Comment (saschagrunert) [inline test/suite_test.go:117]: Let's create a new variable for the SHA (based on the operating system) and factor out the string building to avoid the code duplication.

Comment (naveensrinivasan) [reply test/suite_test.go:116]: It is just not SHA. It is also the platform `kind-darwin-amd64` and `kind-linux`. This will end up with a bunch of string formatting.  

I agree code duplication is not encouraged, but this helps in readability. Thoughts?

Comment (naveensrinivasan) [reply test/suite_test.go]: Took care of it. Thanks

File: Makefile (hunk 1 above)
Comment (naveensrinivasan) [reply Makefile]: Agreed. Thanks

**Review by saschagrunert — COMMENTED** [review]
LGTM, thank you! Can you please squash your commits into a single one? :innocent:

**Comment by naveensrinivasan** [comment]
> LGTM, thank you! Can you please squash your commits into a single one? 😇

I can do, that.

**Review by saschagrunert — APPROVED** [review]
Changes LGTM, can you please drop the merge commit from this PR?

**Comment by jhrozek** [comment]
While I don't have a super strong opinion one way or the other (in fact I did similar patches for other operators because we were getting issues from macOS users), I wonder if you have considered using something like VSCode with its remote plugin. That allows to use e.g. a Linux VM and edit and develop there.

**Comment by naveensrinivasan** [comment]
> While I don't have a super strong opinion one way or the other (in fact I did similar patches for other operators because we were getting issues from macOS users), I wonder if you have considered using something like VSCode with its remote plugin. That allows to use e.g. a Linux VM and edit and develop there.

I have thought about it. I use vim as the editor. But decided not to know because that brings in another dependency to sync all the tools and settings like vimrc, brew bundle, git settings, etc. I find the current situation very easy. It flows very well with my current setup.
